{"type": "DEBUG", "message": "Debug logs enabled", "data": {}}
{"type": "LOG", "log": {"level": "INFO", "message": "Starting syncing SourceServicenowHttpExample"}}
debug here to see if we have access to stream for incidents
debug here to see if we have access to configs
{"type": "LOG", "log": {"level": "ERROR", "message": "{\"error\":{\"message\":\"Requested URI does not represent any resource\",\"detail\":null},\"status\":\"failure\"}"}}
{"type": "LOG", "log": {"level": "ERROR", "message": "Encountered an exception while reading stream incidents\nTraceback (most recent call last):\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 113, in read\n    stream_is_available, reason = stream_instance.check_availability(logger, self)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py\", line 193, in check_availability\n    return self.availability_strategy.check_availability(self, logger, source)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 56, in check_availability\n    is_available, reason = self.handle_http_error(stream, logger, source, error)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 85, in handle_http_error\n    raise error\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 50, in check_availability\n    get_first_record_for_slice(stream, stream_slice)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py\", line 38, in get_first_record_for_slice\n    return next(records_for_slice)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 450, in read_records\n    yield from self._read_pages(\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 466, in _read_pages\n    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 492, in _fetch_next_page\n    response = self._send_request(request, request_kwargs)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 390, in _send_request\n    return backoff_handler(user_backoff_handler)(request, request_kwargs)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 357, in _send\n    raise exc\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 354, in _send\n    response.raise_for_status()\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://dev97596.service-now.com/api/now/incident?sysparm_display_value=true&sysparm_fields=number%2Csys_updated_on%2Csys_id%2Ccategory%2Cstate%2Cclosed_at%2Cactive%2Cclose_notes%2Cdescription%2Ccontact_type&sysparm_exclude_reference_link=true&sysparm_limit=10&sysparm_query=sys_updated_on%3Ejavascript%3Ags.dateGenerate%28%25272023-07-18%2527%252C%252715%3A00%3A00%2527%29%255EORDERBYsys_updated_on"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Marking stream incidents as STOPPED"}}
{"type": "TRACE", "trace": {"type": "STREAM_STATUS", "emitted_at": 1694465345102.278, "stream_status": {"stream_descriptor": {"name": "incidents", "namespace": null}, "status": "INCOMPLETE"}}}
{"type": "LOG", "log": {"level": "INFO", "message": "Finished syncing incidents"}}
{"type": "LOG", "log": {"level": "INFO", "message": "SourceServicenowHttpExample runtimes:\nSyncing stream incidents 0:00:00.286394"}}
{"type": "LOG", "log": {"level": "FATAL", "message": "400 Client Error: Bad Request for url: https://dev97596.service-now.com/api/now/incident?sysparm_display_value=true&sysparm_fields=number%2Csys_updated_on%2Csys_id%2Ccategory%2Cstate%2Cclosed_at%2Cactive%2Cclose_notes%2Cdescription%2Ccontact_type&sysparm_exclude_reference_link=true&sysparm_limit=10&sysparm_query=sys_updated_on%3Ejavascript%3Ags.dateGenerate%28%25272023-07-18%2527%252C%252715%3A00%3A00%2527%29%255EORDERBYsys_updated_on\nTraceback (most recent call last):\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 113, in read\n    stream_is_available, reason = stream_instance.check_availability(logger, self)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py\", line 193, in check_availability\n    return self.availability_strategy.check_availability(self, logger, source)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 56, in check_availability\n    is_available, reason = self.handle_http_error(stream, logger, source, error)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 85, in handle_http_error\n    raise error\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 50, in check_availability\n    get_first_record_for_slice(stream, stream_slice)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py\", line 38, in get_first_record_for_slice\n    return next(records_for_slice)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 450, in read_records\n    yield from self._read_pages(\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 466, in _read_pages\n    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 492, in _fetch_next_page\n    response = self._send_request(request, request_kwargs)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 390, in _send_request\n    return backoff_handler(user_backoff_handler)(request, request_kwargs)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 357, in _send\n    raise exc\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 354, in _send\n    response.raise_for_status()\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://dev97596.service-now.com/api/now/incident?sysparm_display_value=true&sysparm_fields=number%2Csys_updated_on%2Csys_id%2Ccategory%2Cstate%2Cclosed_at%2Cactive%2Cclose_notes%2Cdescription%2Ccontact_type&sysparm_exclude_reference_link=true&sysparm_limit=10&sysparm_query=sys_updated_on%3Ejavascript%3Ags.dateGenerate%28%25272023-07-18%2527%252C%252715%3A00%3A00%2527%29%255EORDERBYsys_updated_on\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/main.py\", line 13, in <module>\n    launch(source, sys.argv[1:])\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 200, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 114, in run\n    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.read(source_spec, config, config_catalog, state))\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 156, in read\n    yield from self.source.read(self.logger, config, catalog, state)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 138, in read\n    raise AirbyteTracedException.from_exception(e, message=display_message) from e\nairbyte_cdk.utils.traced_exception.AirbyteTracedException: 400 Client Error: Bad Request for url: https://dev97596.service-now.com/api/now/incident?sysparm_display_value=true&sysparm_fields=number%2Csys_updated_on%2Csys_id%2Ccategory%2Cstate%2Cclosed_at%2Cactive%2Cclose_notes%2Cdescription%2Ccontact_type&sysparm_exclude_reference_link=true&sysparm_limit=10&sysparm_query=sys_updated_on%3Ejavascript%3Ags.dateGenerate%28%25272023-07-18%2527%252C%252715%3A00%3A00%2527%29%255EORDERBYsys_updated_on"}}
{"type": "TRACE", "trace": {"type": "ERROR", "emitted_at": 1694465345104.8638, "error": {"message": "Requested URI does not represent any resource", "internal_message": "400 Client Error: Bad Request for url: https://dev97596.service-now.com/api/now/incident?sysparm_display_value=true&sysparm_fields=number%2Csys_updated_on%2Csys_id%2Ccategory%2Cstate%2Cclosed_at%2Cactive%2Cclose_notes%2Cdescription%2Ccontact_type&sysparm_exclude_reference_link=true&sysparm_limit=10&sysparm_query=sys_updated_on%3Ejavascript%3Ags.dateGenerate%28%25272023-07-18%2527%252C%252715%3A00%3A00%2527%29%255EORDERBYsys_updated_on", "stack_trace": "Traceback (most recent call last):\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 113, in read\n    stream_is_available, reason = stream_instance.check_availability(logger, self)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py\", line 193, in check_availability\n    return self.availability_strategy.check_availability(self, logger, source)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 56, in check_availability\n    is_available, reason = self.handle_http_error(stream, logger, source, error)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 85, in handle_http_error\n    raise error\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 50, in check_availability\n    get_first_record_for_slice(stream, stream_slice)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py\", line 38, in get_first_record_for_slice\n    return next(records_for_slice)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 450, in read_records\n    yield from self._read_pages(\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 466, in _read_pages\n    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 492, in _fetch_next_page\n    response = self._send_request(request, request_kwargs)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 390, in _send_request\n    return backoff_handler(user_backoff_handler)(request, request_kwargs)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 357, in _send\n    raise exc\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 354, in _send\n    response.raise_for_status()\n  File \"/Users/bryanbarnard/Dev/sandbox/airbyte/airbyte-integrations/connectors/source-servicenow-http-example/.venv/lib/python3.9/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://dev97596.service-now.com/api/now/incident?sysparm_display_value=true&sysparm_fields=number%2Csys_updated_on%2Csys_id%2Ccategory%2Cstate%2Cclosed_at%2Cactive%2Cclose_notes%2Cdescription%2Ccontact_type&sysparm_exclude_reference_link=true&sysparm_limit=10&sysparm_query=sys_updated_on%3Ejavascript%3Ags.dateGenerate%28%25272023-07-18%2527%252C%252715%3A00%3A00%2527%29%255EORDERBYsys_updated_on\n", "failure_type": "system_error"}}}
